### ISSUE TITLE
Github Identified dependency vulnerability

### ISSUE THREAD

**Issue by clcollins** [CommunityHoneyNetwork/mnemosyne#20]
Github has identified a potential vulnerability issue with our dependency on `dlitz/pycrypto` in the `requirements.txt`.

https://github.com/CommunityHoneyNetwork/mnemosyne/network/dependencies

**Comment by clcollins** [comment]
@amerck: Can you please review this?

**Comment by JesseBowling** [comment]
Discussed with @amerck and it does not appear that the vulnerable code is used in this project. That said, lack of a patched version lends more weight to the argument for replacing or removing mnemosyne.

If amerck agrees this is accurate, I suggest we close this as wontfix.

**Comment by JesseBowling** [comment]
Closing wontfix
